unit Infrastructure.Database.Oracle;

interface

uses
  System.SysUtils,
  System.Classes,
  System.JSON,
  Core.Interfaces,
  Data.DB,
  FireDAC.Comp.Client,
  FireDAC.Stan.Intf,
  FireDAC.Stan.Option,
  FireDAC.Stan.Error,
  FireDAC.UI.Intf,
  FireDAC.Phys.Intf,
  FireDAC.Stan.Def,
  FireDAC.Stan.Pool,
  FireDAC.Stan.Async,
  FireDAC.Stan.Param,
  FireDAC.Phys,
  FireDAC.Phys.ODBCBase,
  FireDAC.Phys.ODBCCli,
  FireDAC.Phys.ODBCWrapper,
  FireDAC.DApt,
{$IFDEF FMX}
  FireDAC.FMXUI.Wait;
{$ELSE}
  FireDAC.VCLUI.Wait;
{$ENDIF}

type
  TDbOracleManager = class(TInterfacedObject, IDatabaseManager)
  private
    FLogger: IAppLogger;
    function GetPooledConnection: TFDConnection;
  public
    constructor Create(const ALogger: IAppLogger);
    class procedure InitializePool(const AConnectionString: string);
    class procedure DestroyPool;
    class procedure InitializeDatabase;
    function GetRecordCount: Integer;
    function GetLastRecordId: Integer;
    function GetDataAsJson: string;
    function GetAllDataAsJsonArray: string;
    procedure SaveData(const AJsonData: string);
    procedure UpdateData(AId: Integer; const ANewJson: string);
  end;

const
  POOL_DEF_NAME_ORACLE = 'MyDataSyncPool_Oracle';

implementation

constructor TDbOracleManager.Create(const ALogger: IAppLogger);
begin
  inherited Create;
  FLogger := ALogger;
end;

class procedure TDbOracleManager.InitializeDatabase;
var
  LConn: TFDConnection;
begin
  LConn := TFDConnection.Create(nil);
  try
    LConn.ConnectionDefName := POOL_DEF_NAME_ORACLE;
    LConn.Open;

    // W Oracle nie ma IF NOT EXISTS. Łapiemy błąd ORA-00955 (Name is already used)
    LConn.ExecSQL('BEGIN ' + '  EXECUTE IMMEDIATE ''CREATE TABLE MyTable (' +
      '    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' + '    Data CLOB NOT NULL, ' +
      '    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''; ' + 'EXCEPTION ' + '  WHEN OTHERS THEN ' +
      '    IF SQLCODE != -955 THEN RAISE; END IF; ' + 'END;');
  finally
    LConn.Free;
  end;
end;

class procedure TDbOracleManager.InitializePool(const AConnectionString: string);
var
  LParams: TStringList;
begin
  LParams := TStringList.Create;
  try
    // Parsujemy connection string (np. User_Name=admin;Password=tajne;Database=MY_TNS)
    LParams.Text := StringReplace(AConnectionString, ';', sLineBreak, [rfReplaceAll]);
    LParams.Add('DriverID=Ora');
    LParams.Add('Pooled=True');
    LParams.Add('POOL_MaximumItems=50');

    FDManager.AddConnectionDef(POOL_DEF_NAME_ORACLE, 'Oracle', LParams);
    FDManager.Active := True;
  finally
    LParams.Free;
  end;
end;

class procedure TDbOracleManager.DestroyPool;
begin
  FDManager.Close;
end;

function TDbOracleManager.GetPooledConnection: TFDConnection;
begin
  Result := TFDConnection.Create(nil);
  Result.ConnectionDefName := POOL_DEF_NAME_ORACLE;
  Result.Open;
end;

procedure TDbOracleManager.SaveData(const AJsonData: string);
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LConn.StartTransaction;
      try
        LQuery.SQL.Text := 'INSERT INTO MyTable (Data) VALUES (:data)';
        LQuery.ParamByName('data').AsString := AJsonData; // FireDAC zmapuje to poprawnie na CLOB
        LQuery.ExecSQL;
        LConn.Commit;
      except
        on E: Exception do
        begin
          LConn.Rollback;
          FLogger.LogError('Błąd zapisu do Oracle: ' + E.Message, E);
          raise;
        end;
      end;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

procedure TDbOracleManager.UpdateData(AId: Integer; const ANewJson: string);
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LConn.StartTransaction;
      try
        LQuery.SQL.Text := 'UPDATE MyTable SET Data = :data WHERE Id = :id';
        LQuery.ParamByName('data').AsString := ANewJson;
        LQuery.ParamByName('id').AsInteger := AId;
        LQuery.ExecSQL;
        LConn.Commit;
      except
        on E: Exception do
        begin
          LConn.Rollback;
          FLogger.LogError('Błąd aktualizacji w Oracle: ' + E.Message, E);
          raise;
        end;
      end;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

function TDbOracleManager.GetRecordCount: Integer;
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  Result := 0;
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LQuery.SQL.Text := 'SELECT COUNT(Id) AS Cnt FROM MyTable';
      LQuery.Open;
      Result := LQuery.FieldByName('Cnt').AsInteger;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

function TDbOracleManager.GetLastRecordId: Integer;
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  Result := 0;
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LQuery.SQL.Text := 'SELECT MAX(Id) AS MaxId FROM MyTable';
      LQuery.Open;
      if not LQuery.FieldByName('MaxId').IsNull then
        Result := LQuery.FieldByName('MaxId').AsInteger;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

function TDbOracleManager.GetDataAsJson: string;
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  Result := '';
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      // Dialekt Oracle (wersja 12c i nowsze) dla LIMIT 1
      LQuery.SQL.Text := 'SELECT Data FROM MyTable ORDER BY Id DESC FETCH FIRST 1 ROWS ONLY';
      LQuery.Open;
      if not LQuery.IsEmpty then
        Result := LQuery.FieldByName('Data').AsString;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

function TDbOracleManager.GetAllDataAsJsonArray: string;
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
  LJsonArray: TJSONArray;
  LJsonRow: TJSONObject;
begin
  Result := '[]';
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LQuery.SQL.Text := 'SELECT Id, Data, CreatedAt FROM MyTable ORDER BY Id DESC';
      LQuery.Open;

      LJsonArray := TJSONArray.Create;
      try
        while not LQuery.Eof do
        begin
          LJsonRow := TJSONObject.Create;
          try
            LJsonRow.AddPair('id', TJSONNumber.Create(LQuery.FieldByName('Id').AsInteger));
            LJsonRow.AddPair('data', LQuery.FieldByName('Data').AsString);
            LJsonRow.AddPair('created_at', LQuery.FieldByName('CreatedAt').AsString);
            LJsonArray.AddElement(LJsonRow);
            LJsonRow := nil; // TJSONArray przejmuje zwalnianie obiektu
          finally
            LJsonRow.Free; // Wolne tylko w przypadku wystąpienia Exception przed AddElement
          end;
          LQuery.Next;
        end;
        Result := LJsonArray.ToJSON;
      finally
        LJsonArray.Free;
      end;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

end.
