unit Infrastructure.Database.Firebird;

interface

uses
  System.SysUtils,
  System.Classes,
  System.JSON,
  Core.Interfaces,
  Data.DB,
  FireDAC.Comp.Client,
  FireDAC.Stan.Intf,
  FireDAC.Stan.Option,
  FireDAC.Stan.Error,
  FireDAC.UI.Intf,
  FireDAC.Phys.Intf,
  FireDAC.Stan.Def,
  FireDAC.Stan.Pool,
  FireDAC.Stan.Async,
  FireDAC.Stan.Param,
  FireDAC.Phys,
  FireDAC.Phys.FB,
  FireDAC.Phys.FBDef,
  FireDAC.DApt,
{$IFDEF FMX}
  FireDAC.FMXUI.Wait;
{$ELSE}
  FireDAC.VCLUI.Wait;
{$ENDIF}

type
  TDbFirebirdManager = class(TInterfacedObject, IDatabaseManager)
  private
    FLogger: IAppLogger;
    function GetPooledConnection: TFDConnection;
  public
    constructor Create(const ALogger: IAppLogger);
    class procedure InitializePool(const AConnectionString: string);
    class procedure DestroyPool;
    class procedure InitializeDatabase;
    function GetRecordCount: Integer;
    function GetLastRecordId: Integer;
    function GetDataAsJson: string;
    function GetAllDataAsJsonArray: string;
    procedure SaveData(const AJsonData: string);
    procedure UpdateData(AId: Integer; const ANewJson: string);
  end;

const
  POOL_DEF_NAME_FB = 'MyDataSyncPool_FB';

implementation

constructor TDbFirebirdManager.Create(const ALogger: IAppLogger);
begin
  inherited Create;
  FLogger := ALogger;
end;

class procedure TDbFirebirdManager.InitializeDatabase;
var
  LConn: TFDConnection;
begin
  LConn := TFDConnection.Create(nil);
  try
    LConn.ConnectionDefName := POOL_DEF_NAME_FB;
    LConn.Open;

    // Firebird EXECUTE BLOCK używany jako odpowiednik IF NOT EXISTS
    LConn.ExecSQL('EXECUTE BLOCK AS BEGIN ' +
      '  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = ''MYTABLE'')) THEN ' +
      '  EXECUTE STATEMENT ''CREATE TABLE MYTABLE (' + '    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' +
      '    Data BLOB SUB_TYPE TEXT NOT NULL, ' + '    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''; ' + 'END');
  finally
    LConn.Free;
  end;
end;

class procedure TDbFirebirdManager.InitializePool(const AConnectionString: string);
var
  LParams: TStringList;
begin
  LParams := TStringList.Create;
  try
    LParams.Text := StringReplace(AConnectionString, ';', sLineBreak, [rfReplaceAll]);
    LParams.Add('DriverID=FB');
    LParams.Add('Pooled=True');
    LParams.Add('POOL_MaximumItems=50');

    FDManager.AddConnectionDef(POOL_DEF_NAME_FB, 'FB', LParams);
    FDManager.Active := True;
  finally
    LParams.Free;
  end;
end;

class procedure TDbFirebirdManager.DestroyPool;
begin
  FDManager.Close;
end;

function TDbFirebirdManager.GetPooledConnection: TFDConnection;
begin
  Result := TFDConnection.Create(nil);
  Result.ConnectionDefName := POOL_DEF_NAME_FB;
  Result.Open;
end;

procedure TDbFirebirdManager.SaveData(const AJsonData: string);
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LConn.StartTransaction;
      try
        LQuery.SQL.Text := 'INSERT INTO MYTABLE (Data) VALUES (:data)';
        // W Firebird używamy AsString dla wprowadzania danych do BLOB TEXT
        LQuery.ParamByName('data').AsString := AJsonData;
        LQuery.ExecSQL;
        LConn.Commit;
      except
        on E: Exception do
        begin
          LConn.Rollback;
          FLogger.LogError('Błąd zapisu do Firebird: ' + E.Message, E);
          raise;
        end;
      end;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

procedure TDbFirebirdManager.UpdateData(AId: Integer; const ANewJson: string);
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LConn.StartTransaction;
      try
        LQuery.SQL.Text := 'UPDATE MYTABLE SET Data = :data WHERE Id = :id';
        LQuery.ParamByName('data').AsString := ANewJson;
        LQuery.ParamByName('id').AsInteger := AId;
        LQuery.ExecSQL;
        LConn.Commit;
      except
        on E: Exception do
        begin
          LConn.Rollback;
          FLogger.LogError('Błąd aktualizacji w Firebird: ' + E.Message, E);
          raise;
        end;
      end;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

function TDbFirebirdManager.GetRecordCount: Integer;
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  Result := 0;
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LQuery.SQL.Text := 'SELECT COUNT(Id) AS Cnt FROM MYTABLE';
      LQuery.Open;
      Result := LQuery.FieldByName('Cnt').AsInteger;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

function TDbFirebirdManager.GetLastRecordId: Integer;
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  Result := 0;
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LQuery.SQL.Text := 'SELECT MAX(Id) AS MaxId FROM MYTABLE';
      LQuery.Open;
      if not LQuery.FieldByName('MaxId').IsNull then
        Result := LQuery.FieldByName('MaxId').AsInteger;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

function TDbFirebirdManager.GetDataAsJson: string;
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  Result := '';
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      // Dialekt Firebird dla LIMIT 1 (SELECT FIRST 1)
      LQuery.SQL.Text := 'SELECT FIRST 1 Data FROM MYTABLE ORDER BY Id DESC';
      LQuery.Open;
      if not LQuery.IsEmpty then
        Result := LQuery.FieldByName('Data').AsString;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

function TDbFirebirdManager.GetAllDataAsJsonArray: string;
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
  LJsonArray: TJSONArray;
  LJsonRow: TJSONObject;
begin
  Result := '[]';
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LQuery.SQL.Text := 'SELECT Id, Data, CreatedAt FROM MYTABLE ORDER BY Id DESC';
      LQuery.Open;

      LJsonArray := TJSONArray.Create;
      try
        while not LQuery.Eof do
        begin
          LJsonRow := TJSONObject.Create;
          try
            LJsonRow.AddPair('id', TJSONNumber.Create(LQuery.FieldByName('Id').AsInteger));
            LJsonRow.AddPair('data', LQuery.FieldByName('Data').AsString);
            LJsonRow.AddPair('created_at', LQuery.FieldByName('CreatedAt').AsString);
            LJsonArray.AddElement(LJsonRow);
            LJsonRow := nil; // TJSONArray przejmuje obiekt
          finally
            LJsonRow.Free;
          end;
          LQuery.Next;
        end;
        Result := LJsonArray.ToJSON;
      finally
        LJsonArray.Free;
      end;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

end.
